---
name: Error-Subclasses
version: 0.03
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: A collection of utility exception subclasses
license: perl
requires:
  Error: 0.15
provides:
  Error::SystemException:
    file: lib/Error/SystemException.pm
generated_by: Module::Build version 0.26
